### ISSUE TITLE
[Research] Rust/operator : raw string lietral 

### ISSUE THREAD

**Issue by developerasun** [developerasun/myCodeBox-blockchain#107]
# topic : understanding raw string literal in Rust
## read this 
> While working with Rust, you will often come across r#"something like this"#, especially when working with JSON and TOML files. It defines a raw string literal. When would you use a raw string literal and what makes a valid raw string literal?

> First, let’s understand what a string literal is. According to the The Rust Reference[1](https://rahul-thakoor.github.io/rust-raw-string-literals/#fn:1), A string literal is a sequence of any Unicode characters enclosed within two U+00[2](https://rahul-thakoor.github.io/rust-raw-string-literals/#fn:2)2 (double-quote) characters, with the exception of U+0022 itself2. Escape characters in the string literal body are processed. The string body cannot contain a double-quote. If you need to insert one, you have to escape it like this: \".

> Escaping double-quotes can be cumbersome in some cases such as writing regular expressions or defining a JSON object as a string literal. In these situations, raw string literals are helpful since they allow you to write the literal without requiring escapes.

```toml
let toml_str = r#"
        global_string = "test"
        global_integer = 5
        [server]
        ip = "127.0.0.1"
        port = 80
        [[peers]]
        ip = "127.0.0.1"
        port = 8080
        [[peers]]
        ip = "127.0.0.1"
    "#;
```

> Escape characters in the raw string body are not processed.

## reference
- https://rahul-thakoor.github.io/rust-raw-string-literals/
